// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using PulsePilot.Infrastructure.Persistence;

#nullable disable

namespace PulsePilot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812135419_AddFeedbackClusterPriority")]
    partial class AddFeedbackClusterPriority
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PulsePilot.Domain.Feedback.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("customer_name");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("FeedbackClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_cluster_id");

                    b.Property<Guid?>("ProcessingLeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("processing_lease_id");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("processing_status");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_feedback");

                    b.HasAlternateKey("WorkspaceId", "Id")
                        .HasName("ak_feedback_workspace_id_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_feedback_created_by_user_id");

                    b.HasIndex("ProcessingStatus", "ProcessingStartedAt")
                        .HasDatabaseName("ix_feedback_processing_status_started_at");

                    b.HasIndex("WorkspaceId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_feedback_workspace_id_created_at");

                    b.HasIndex("WorkspaceId", "FeedbackClusterId")
                        .HasDatabaseName("ix_feedback_workspace_id_cluster_id");

                    b.HasIndex("WorkspaceId", "ProcessingStatus")
                        .HasDatabaseName("ix_feedback_workspace_id_processing_status");

                    b.ToTable("feedback", null, t =>
                        {
                            t.HasCheckConstraint("ck_feedback_processing_lease", "(processing_status = 'Processing' AND processing_lease_id IS NOT NULL AND processing_started_at IS NOT NULL) OR (processing_status <> 'Processing' AND processing_lease_id IS NULL AND processing_started_at IS NULL)");

                            t.HasCheckConstraint("ck_feedback_processing_status", "processing_status IN ('Pending', 'Processing', 'Completed', 'Failed')");

                            t.HasCheckConstraint("ck_feedback_source", "source IN ('Manual', 'Email', 'Support', 'Survey', 'Api', 'AppReview')");
                        });
                });

            modelBuilder.Entity("PulsePilot.Domain.Feedback.FeedbackAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("component");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sentiment");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<string>("SuggestedAction")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("suggested_action");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_feedback_analyses");

                    b.HasIndex("WorkspaceId", "FeedbackId")
                        .IsUnique()
                        .HasDatabaseName("ux_feedback_analyses_workspace_id_feedback_id");

                    b.ToTable("feedback_analyses", null, t =>
                        {
                            t.HasCheckConstraint("ck_feedback_analyses_category", "category IN ('Bug', 'FeatureRequest', 'Complaint', 'Question', 'Praise', 'Other')");

                            t.HasCheckConstraint("ck_feedback_analyses_component", "component IN ('Payments', 'Authentication', 'Dashboard', 'Reporting', 'Mobile', 'Api', 'Performance', 'General')");

                            t.HasCheckConstraint("ck_feedback_analyses_confidence", "confidence BETWEEN 0 AND 1");

                            t.HasCheckConstraint("ck_feedback_analyses_sentiment", "sentiment IN ('Positive', 'Neutral', 'Negative')");

                            t.HasCheckConstraint("ck_feedback_analyses_severity", "severity BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("PulsePilot.Domain.Feedback.FeedbackCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("component");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("priority");

                    b.Property<decimal>("PriorityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("priority_score");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_feedback_clusters");

                    b.HasAlternateKey("WorkspaceId", "Id")
                        .HasName("ak_feedback_clusters_workspace_id_id");

                    b.HasIndex("WorkspaceId", "PriorityScore")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_feedback_clusters_workspace_id_priority_score");

                    b.HasIndex("WorkspaceId", "UpdatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_feedback_clusters_workspace_id_updated_at");

                    b.HasIndex("WorkspaceId", "Category", "Component")
                        .HasDatabaseName("ix_feedback_clusters_workspace_category_component");

                    b.ToTable("feedback_clusters", null, t =>
                        {
                            t.HasCheckConstraint("ck_feedback_clusters_category", "category IN ('Bug', 'FeatureRequest', 'Complaint', 'Question', 'Praise', 'Other')");

                            t.HasCheckConstraint("ck_feedback_clusters_component", "component IN ('Payments', 'Authentication', 'Dashboard', 'Reporting', 'Mobile', 'Api', 'Performance', 'General')");

                            t.HasCheckConstraint("ck_feedback_clusters_priority", "priority IN ('P1', 'P2', 'P3', 'P4')");

                            t.HasCheckConstraint("ck_feedback_clusters_priority_score", "priority_score BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("PulsePilot.Domain.Feedback.FeedbackEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("source_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<Vector>("_values")
                        .IsRequired()
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.HasKey("Id")
                        .HasName("pk_feedback_embeddings");

                    b.HasIndex("_values")
                        .HasDatabaseName("ix_feedback_embeddings_embedding_cosine")
                        .HasAnnotation("Npgsql:StorageParameter:ef_construction", 64)
                        .HasAnnotation("Npgsql:StorageParameter:m", 16);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("_values"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("_values"), new[] { "vector_cosine_ops" });

                    b.HasIndex("WorkspaceId", "FeedbackId")
                        .IsUnique()
                        .HasDatabaseName("ux_feedback_embeddings_workspace_id_feedback_id");

                    b.ToTable("feedback_embeddings", (string)null);
                });

            modelBuilder.Entity("PulsePilot.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PulsePilot.Domain.Workspaces.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("PulsePilot.Domain.Workspaces.WorkspaceMember", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.HasKey("WorkspaceId", "UserId")
                        .HasName("pk_workspace_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_workspace_members_user_id");

                    b.ToTable("workspace_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_workspace_members_role", "role IN ('Admin', 'Member')");
                        });
                });

            modelBuilder.Entity("PulsePilot.Domain.Feedback.Feedback", b =>
                {
                    b.HasOne("PulsePilot.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_users_created_by_user_id");

                    b.HasOne("PulsePilot.Domain.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_workspaces_workspace_id");

                    b.HasOne("PulsePilot.Domain.Feedback.FeedbackCluster", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "FeedbackClusterId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_feedback_clusters_workspace_id_cluster_id");
                });

            modelBuilder.Entity("PulsePilot.Domain.Feedback.FeedbackAnalysis", b =>
                {
                    b.HasOne("PulsePilot.Domain.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_analyses_workspaces_workspace_id");

                    b.HasOne("PulsePilot.Domain.Feedback.Feedback", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "FeedbackId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_analyses_feedback_workspace_id_feedback_id");
                });

            modelBuilder.Entity("PulsePilot.Domain.Feedback.FeedbackCluster", b =>
                {
                    b.HasOne("PulsePilot.Domain.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_clusters_workspaces_workspace_id");
                });

            modelBuilder.Entity("PulsePilot.Domain.Feedback.FeedbackEmbedding", b =>
                {
                    b.HasOne("PulsePilot.Domain.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_embeddings_workspaces_workspace_id");

                    b.HasOne("PulsePilot.Domain.Feedback.Feedback", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "FeedbackId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_embeddings_feedback_workspace_id_feedback_id");
                });

            modelBuilder.Entity("PulsePilot.Domain.Workspaces.WorkspaceMember", b =>
                {
                    b.HasOne("PulsePilot.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_users_user_id");

                    b.HasOne("PulsePilot.Domain.Workspaces.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_workspaces_workspace_id");
                });
#pragma warning restore 612, 618
        }
    }
}
